### PR TITLE
Balancer and mStable support

### PR DESCRIPTION
**Pull request by marcelomorgado**

### CODE REVIEW

**Comment by adrianmcli** [comment]
@marcelomorgado really excellent stuff. I'll keep watching this!

**Comment by marcelomorgado** [comment]
> @marcelomorgado really excellent stuff. I'll keep watching this!

Thanks @adrianmcli! It's ready to be merged IMO.

Best

**Comment by marcelomorgado** [comment]
I'll continue to push fixes here when it's open but you can merge this IMO, if new bugs appear I can create further PRs.

**Comment by adrianmcli** [comment]
@marcelomorgado great, I will review this over the weekend!

**Comment by adrianmcli** [comment]
Sorry for the delay. This is quite an impressive PR and it looks like it checks out to me! Thanks again @marcelomorgado

**Pull request merged**
